using System.Data.Common;
using Microsoft.Extensions.Configuration;

namespace Api.Infrastructure;

public static class DatabaseMigrator
{
    public static async Task MigrateSqliteToPostgresAsync(IConfiguration configuration, CancellationToken cancellationToken = default)
    {
        var sourceConnectionString =
            Environment.GetEnvironmentVariable("SQLITE_CONNECTION_STRING")
            ?? configuration.GetConnectionString("Sqlite")
            ?? configuration["Database:SqliteConnectionString"]
            ?? "Data Source=ingestion.db";

        var targetConnectionString =
            Environment.GetEnvironmentVariable("POSTGRES_CONNECTION_STRING")
            ?? configuration.GetConnectionString("Postgres")
            ?? configuration["Database:PostgresConnectionString"];

        if (string.IsNullOrWhiteSpace(targetConnectionString))
        {
            throw new InvalidOperationException("POSTGRES_CONNECTION_STRING is required for migration.");
        }

        var source = new DatabaseOptions("sqlite", sourceConnectionString, null);
        var target = new DatabaseOptions("postgres", targetConnectionString, null);

        await using var sourceConn = source.CreateConnection();
        await using var targetConn = target.CreateConnection();
        await sourceConn.OpenAsync(cancellationToken);
        await targetConn.OpenAsync(cancellationToken);

        await EnsurePostgresSchemaAsync(targetConn, cancellationToken);
        await ClearPostgresDataAsync(targetConn, cancellationToken);

        await CopyTableAsync(sourceConn, targetConn, "Users", new[]
        {
            "Id", "Email", "PasswordHash", "CreatedAt", "FullName", "IsSuperUser"
        }, cancellationToken);

        await CopyTableAsync(sourceConn, targetConn, "Sessions", new[]
        {
            "Id", "UserId", "UploadId", "ClassId", "CreatedAt"
        }, cancellationToken);

        await CopyTableAsync(sourceConn, targetConn, "Messages", new[]
        {
            "Id", "SessionId", "Role", "Content", "Citations", "PagesUsed", "CreatedAt"
        }, cancellationToken);

        await CopyTableAsync(sourceConn, targetConn, "Notes", new[]
        {
            "Id", "UserId", "SessionId", "UploadId", "Text", "CreatedAt"
        }, cancellationToken);

        await CopyTableAsync(sourceConn, targetConn, "Uploads", new[]
        {
            "UploadId", "UserId", "FilePath", "Name", "OriginalFileName", "CreatedAt"
        }, cancellationToken);

        await CopyTableAsync(sourceConn, targetConn, "Classes", new[]
        {
            "Id", "InstructorId", "Name", "Description", "JoinCode", "CreatedAt"
        }, cancellationToken);

        await CopyTableAsync(sourceConn, targetConn, "ClassStudents", new[]
        {
            "ClassId", "StudentId", "AddedAt"
        }, cancellationToken);

        await CopyTableAsync(sourceConn, targetConn, "ClassCases", new[]
        {
            "ClassId", "UploadId", "Objective", "Focus", "DueAt", "ReadingCoachQuestions", "AssignedAt"
        }, cancellationToken);

        await CopyTableAsync(sourceConn, targetConn, "TutorSessions", new[]
        {
            "SessionId", "UserId", "UploadId", "Category", "Focus", "CurrentNode",
            "VisitedTopicsJson", "VisitedPagesJson", "HistoryJson", "LastStepSummary",
            "DrillPathJson", "PendingDrillChoicesJson", "CreatedAt", "UpdatedAt"
        }, cancellationToken);

        await CopyTableAsync(sourceConn, targetConn, "TutorAnswers", new[]
        {
            "Id", "SessionId", "UserId", "UploadId", "StepId", "Question", "Answer",
            "Feedback", "Score", "CreatedAt"
        }, cancellationToken);

        await CopyTableAsync(sourceConn, targetConn, "TutorHelpEvents", new[]
        {
            "Id", "UserId", "UploadId", "ChatSessionId", "TutorSessionId", "StepId",
            "Question", "CreatedAt"
        }, cancellationToken);

        await EnsureBackgroundJobTableAsync(targetConn, cancellationToken);
    }

    private static async Task EnsurePostgresSchemaAsync(DbConnection target, CancellationToken cancellationToken)
    {
        await using var cmd = target.CreateCommand();
        cmd.CommandText = @"
CREATE TABLE IF NOT EXISTS Users (
  Id TEXT PRIMARY KEY,
  Email TEXT NOT NULL UNIQUE,
  PasswordHash TEXT NOT NULL,
  CreatedAt TEXT NOT NULL,
  FullName TEXT NULL,
  IsSuperUser INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Sessions (
  Id TEXT PRIMARY KEY,
  UserId TEXT NOT NULL,
  UploadId TEXT NULL,
  ClassId TEXT NULL,
  CreatedAt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Messages (
  Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  SessionId TEXT NOT NULL,
  Role TEXT NOT NULL,
  Content TEXT NOT NULL,
  Citations TEXT NULL,
  PagesUsed TEXT NULL,
  CreatedAt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Notes (
  Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  UserId TEXT NOT NULL,
  SessionId TEXT NULL,
  UploadId TEXT NULL,
  Text TEXT NOT NULL,
  CreatedAt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Uploads (
  UploadId TEXT PRIMARY KEY,
  UserId TEXT NOT NULL,
  FilePath TEXT NOT NULL,
  Name TEXT NULL,
  OriginalFileName TEXT NULL,
  CreatedAt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Classes (
  Id TEXT PRIMARY KEY,
  InstructorId TEXT NOT NULL,
  Name TEXT NOT NULL,
  Description TEXT NULL,
  JoinCode TEXT NULL,
  CreatedAt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ClassStudents (
  ClassId TEXT NOT NULL,
  StudentId TEXT NOT NULL,
  AddedAt TEXT NOT NULL,
  PRIMARY KEY (ClassId, StudentId)
);

CREATE TABLE IF NOT EXISTS ClassCases (
  ClassId TEXT NOT NULL,
  UploadId TEXT NOT NULL,
  Objective TEXT NULL,
  Focus TEXT NULL,
  DueAt TEXT NULL,
  ReadingCoachQuestions TEXT NULL,
  AssignedAt TEXT NOT NULL,
  PRIMARY KEY (ClassId, UploadId)
);

CREATE TABLE IF NOT EXISTS TutorSessions (
  SessionId TEXT PRIMARY KEY,
  UserId TEXT NOT NULL,
  UploadId TEXT NOT NULL,
  Category TEXT NOT NULL,
  Focus TEXT NULL,
  CurrentNode TEXT NOT NULL,
  VisitedTopicsJson TEXT NOT NULL,
  VisitedPagesJson TEXT NOT NULL,
  HistoryJson TEXT NOT NULL,
  LastStepSummary TEXT NULL,
  DrillPathJson TEXT NULL,
  PendingDrillChoicesJson TEXT NULL,
  CreatedAt TEXT NOT NULL,
  UpdatedAt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS TutorAnswers (
  Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  SessionId TEXT NOT NULL,
  UserId TEXT NOT NULL,
  UploadId TEXT NOT NULL,
  StepId TEXT NOT NULL,
  Question TEXT NOT NULL,
  Answer TEXT NOT NULL,
  Feedback TEXT NOT NULL,
  Score REAL NOT NULL,
  CreatedAt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS TutorHelpEvents (
  Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  UserId TEXT NOT NULL,
  UploadId TEXT NOT NULL,
  ChatSessionId TEXT NULL,
  TutorSessionId TEXT NULL,
  StepId TEXT NULL,
  Question TEXT NOT NULL,
  CreatedAt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS IndexJobs (
  UploadId TEXT PRIMARY KEY,
  Status TEXT NOT NULL,
  RequestedBy TEXT NULL,
  CreatedAt TEXT NOT NULL,
  StartedAt TEXT NULL,
  CompletedAt TEXT NULL,
  Attempts INTEGER NOT NULL DEFAULT 0,
  LastError TEXT NULL,
  ResultJson TEXT NULL,
  WorkerId TEXT NULL,
  UpdatedAt TEXT NOT NULL,
  LastHeartbeatAt TEXT NULL
);";
        await cmd.ExecuteNonQueryAsync(cancellationToken);
    }

    private static async Task ClearPostgresDataAsync(DbConnection target, CancellationToken cancellationToken)
    {
        await using var cmd = target.CreateCommand();
        cmd.CommandText = @"
TRUNCATE TABLE
  IndexJobs,
  TutorHelpEvents,
  TutorAnswers,
  TutorSessions,
  ClassCases,
  ClassStudents,
  Classes,
  Uploads,
  Notes,
  Messages,
  Sessions,
  Users
RESTART IDENTITY CASCADE;";
        await cmd.ExecuteNonQueryAsync(cancellationToken);
    }

    private static async Task EnsureBackgroundJobTableAsync(DbConnection target, CancellationToken cancellationToken)
    {
        await using var cmd = target.CreateCommand();
        cmd.CommandText = @"
CREATE TABLE IF NOT EXISTS IndexJobs (
  UploadId TEXT PRIMARY KEY,
  Status TEXT NOT NULL,
  RequestedBy TEXT NULL,
  CreatedAt TEXT NOT NULL,
  StartedAt TEXT NULL,
  CompletedAt TEXT NULL,
  Attempts INTEGER NOT NULL DEFAULT 0,
  LastError TEXT NULL,
  ResultJson TEXT NULL,
  WorkerId TEXT NULL,
  UpdatedAt TEXT NOT NULL,
  LastHeartbeatAt TEXT NULL
);";
        await cmd.ExecuteNonQueryAsync(cancellationToken);
    }

    private static async Task CopyTableAsync(DbConnection source, DbConnection target, string tableName, string[] columns, CancellationToken cancellationToken)
    {
        var columnList = string.Join(", ", columns);
        await using var select = source.CreateCommand();
        select.CommandText = $"SELECT {columnList} FROM {tableName};";

        await using var reader = await select.ExecuteReaderAsync(cancellationToken);
        await using var tx = target.BeginTransaction();

        while (await reader.ReadAsync(cancellationToken))
        {
            await using var insert = target.CreateCommand();
            insert.Transaction = tx;
            insert.CommandText = $"INSERT INTO {tableName} ({columnList}) VALUES ({string.Join(", ", columns.Select(c => "@" + c))});";

            for (var i = 0; i < columns.Length; i++)
            {
                insert.AddWithValue(columns[i], reader.IsDBNull(i) ? DBNull.Value : reader.GetValue(i));
            }

            await insert.ExecuteNonQueryAsync(cancellationToken);
        }

        tx.Commit();
    }
}
